import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import PageContainer from "../components/PageContainer";
import PeopleShowcase from "../components/PeopleShowcase";

export default function Home() {
  const router = useRouter();

  const goToStep2 = () => {
    router.push("/details");
  };

  return (
    <div
      className="h-screen w-screen"
      style={{
        backgroundImage: `url('/bg.png')`,
        backgroundSize: "cover",
      }}
    >
      <Head>
        <title>Sponsor - Atharva Deosthale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer step={1}>
        <div className="text-4xl font-bold">Sponsor me</div>
        <div className="mt-10 text-xl text-gray-500 leading-9">
          Thank you for showing interest in supporting my work! This will keep
          me motivated to do more and create more content that will help more
          and more developers learn their craft and get better at it everyday.
        </div>
        <PeopleShowcase />
        <hr className="mt-14" />
        <div className="mt-10 flex w-full flex-row-reverse">
          <button
            onClick={goToStep2}
            className="bg-blue-500 px-10 py-2 text-lg text-white rounded-md hover:bg-blue-600 transition-all"
          >
            Proceed
          </button>
        </div>
      </PageContainer>
    </div>
  );
}
